In [2]:
import requests
import pandas as pd

## 3. Fetch NVE-data in VSCode

In [3]:

# Link to the API endpoint for Magasinstatistikk data
url = "https://biapi.nve.no/magasinstatistikk/api/Magasinstatistikk/HentOffentligData"

# Make a GET request to the API endpoint with a timeout of 60 seconds
response = requests.get(url, timeout=60)
response.raise_for_status()

# Convert the JSON response into a pandas DataFrame for easier analysis and manipulation
data = response.json()

df = pd.DataFrame(data)

# Overview of the DataFrame
df

,dato_Id,omrType,omrnr,iso_aar,iso_uke,fyllingsgrad,kapasitet_TWh,fylling_TWh,neste_Publiseringsdato,fyllingsgrad_forrige_uke,endring_fyllingsgrad
0,1995-09-03,EL,4,1995,35,0.944721,21.079208,19.913979,0001-01-01T00:00:00,0.936888,0.007833
1,2020-11-15,EL,1,2020,46,0.974361,6.003264,5.849344,2020-11-25T13:00:00,0.997406,-0.023046
2,2011-08-28,EL,4,2011,34,0.786499,21.079208,16.578772,0001-01-01T00:00:00,0.787193,-0.000694
3,1998-07-05,EL,3,1998,27,0.793969,8.920932,7.082947,0001-01-01T00:00:00,0.733812,0.060157
4,2011-03-27,EL,4,2011,12,0.300820,21.079208,6.341054,0001-01-01T00:00:00,0.311122,-0.010301
...,...,...,...,...,...,...,...,...,...,...,...
14917,2026-10-04,VASS,1,2026,40,0.615877,36.044464,22.198960,2026-10-14T13:00:00,0.615329,0.000548
14918,2026-10-11,VASS,3,2026,41,0.855031,28.155403,24.073736,2026-10-21T13:00:00,0.842011,0.013020
14919,2026-10-04,VASS,2,2026,40,0.587470,23.237715,13.651460,2026-10-14T13:00:00,0.585406,0.002064
14920,2026-10-11,VASS,2,2026,41,0.603600,23.237715,14.026281,2026-10-21T13:00:00,0.587470,0.016130
14921,2026-10-11,VASS,1,2026,41,0.621249,36.044464,22.392570,2026-10-21T13:00:00,0.615876,0.005372

Test the ``get_nve_data`` function from ``NVE_API.py``

In [5]:
from NVE_API import get_nve_data


df = get_nve_data(
    start_date="2025-01-01",
    end_date="2025-12-31"
)

df

,dato_Id,omrType,omrnr,iso_aar,iso_uke,fyllingsgrad,kapasitet_TWh,fylling_TWh,neste_Publiseringsdato,fyllingsgrad_forrige_uke,endring_fyllingsgrad
0,2025-01-05,EL,5,2025,1,0.729039,17.390587,12.678409,2025-01-15T13:00:00,0.766172,-0.037133
1,2025-01-05,VASS,1,2025,1,0.743467,36.044464,26.797865,2025-01-15T13:00:00,0.769496,-0.026029
2,2025-01-05,EL,2,2025,1,0.764177,34.043590,26.015335,2025-01-15T13:00:00,0.782341,-0.018164
3,2025-01-05,EL,1,2025,1,0.717326,6.003264,4.306299,2025-01-15T13:00:00,0.752098,-0.034771
4,2025-01-05,VASS,3,2025,1,0.804048,28.155403,22.638300,2025-01-15T13:00:00,0.818824,-0.014775
...,...,...,...,...,...,...,...,...,...,...,...
463,2025-12-28,EL,4,2025,52,0.853565,21.079208,17.992483,2026-01-07T13:00:00,0.848353,0.005212
464,2025-12-28,EL,5,2025,52,0.692902,17.390587,12.049965,2026-01-07T13:00:00,0.726427,-0.033525
465,2025-12-28,EL,1,2025,52,0.718576,6.003264,4.313799,2026-01-07T13:00:00,0.756103,-0.037528
466,2025-12-28,VASS,1,2025,52,0.690699,36.044464,24.895876,2026-01-07T13:00:00,0.722843,-0.032144
467,2025-12-28,EL,2,2025,52,0.654828,34.043590,22.292704,2026-01-07T13:00:00,0.677376,-0.022548